# Generated by Django 2.2.3 on 2019-07-06 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datas_disponíveis', models.DateTimeField()),
                ('data_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.Carro')),
            ],
        ),
    ]
