# Generated by Django 2.2.3 on 2019-07-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='data_carro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carro.Carro'),
        ),
    ]
