# Generated by Django 2.2.3 on 2019-07-08 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20190708_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='data_carro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carro.Carro'),
        ),
    ]
