# Generated by Django 2.2.3 on 2019-07-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_auto_20190708_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='datas_disponíveis',
            field=models.DateField(),
        ),
    ]
