# Generated by Django 2.2.3 on 2019-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_auto_20190706_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='datas_disponíveis',
            field=models.ManyToManyField(null=True, to='datas.Datas'),
        ),
    ]
