# Generated by Django 2.2.3 on 2019-07-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0004_auto_20190708_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
