# Generated by Django 2.2.3 on 2019-07-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formas_de_pagamento', models.CharField(choices=[('Cartão de cŕedito', (('Visa cŕedito', 'visa cŕedito'), ('Mastercard crédito', 'mastercard crédito'))), ('Cartão de débito', (('Visa débito', 'visa débito'), ('Mastercard débito', 'mastercard débito'))), ('Dinheiro', 'Real'), ('PicPay', 'Saldo+Cartão'), ('Bitcoin', 'BTC')], max_length=100)),
            ],
        ),
    ]
