# Generated by Django 2.2.3 on 2019-07-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0004_auto_20190710_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
