# Generated by Django 2.2.3 on 2019-07-10 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0005_aluguel_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 22, 54, 28, 240372)),
        ),
    ]
