# Generated by Django 2.2.3 on 2019-07-10 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0006_aluguel_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_inicio',
            field=models.DateField(default=datetime.datetime(2019, 7, 10, 22, 55, 10, 568564, tzinfo=utc)),
        ),
    ]
