# Generated by Django 2.2.3 on 2019-07-10 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluguel', '0007_auto_20190710_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_inicio',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
